import { ApiProperty } from '@nestjs/swagger';
import { IsArray, IsObject, IsOptional, IsString } from 'class-validator';

export class SolvencyProofRequestDto {
  @ApiProperty({
    description: 'Asset balances used to generate solvency proof',
    example: { USDC: '1000', ETH: '2' },
  })
  @IsObject()
  balances: Record<string, string>;

  @ApiProperty({
    description: 'Minimum solvency threshold for the proof',
    example: '1500',
  })
  @IsString()
  threshold: string;
}

export class ProofRequestDto {
  @ApiProperty({
    description: 'Proof object generated by the proving circuit',
  })
  @IsObject()
  proof: Record<string, any>;

  @ApiProperty({
    description: 'Public signals that accompany the proof',
  })
  @IsArray()
  publicSignals: any[];
}

export class ProofResponseDto {
  @ApiProperty({
    description: 'Proof generated by the zero-knowledge circuit',
  })
  proof: Record<string, any>;

  @ApiProperty({
    description: 'Public signals for verification',
  })
  publicSignals: any[];
}
